name: Release Apps

on:
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+(b[0-9]+)?'

jobs:
  node10:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '10.24.1'
    - name: Install dependencies
      run: |
        yarn global add @vue/cli
        yarn install

    - name: Build
      run: yarn build:apps

    - name: Deploy apps
      run: yarn deploy:apps

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: apps-bundle.zip
